CREATE TABLE IF NOT EXISTS `consultancy_cases` (
  `id` char(36) NOT NULL,
  `reference_code` varchar(64) NOT NULL,
  `sales_lead_id` char(36) DEFAULT NULL,
  `company_user_id` char(36) DEFAULT NULL,
  `company_name` varchar(255) NOT NULL,
  `contact_name` varchar(255) NOT NULL,
  `contact_email` varchar(255) NOT NULL,
  `contact_phone` varchar(64) DEFAULT NULL,
  `website_url` longtext,
  `industry` varchar(191) DEFAULT NULL,
  `company_size` varchar(64) DEFAULT NULL,
  `hiring_volume` int NOT NULL DEFAULT 0,
  `hiring_locations` longtext,
  `service_types` json DEFAULT NULL,
  `message` longtext,
  `status` varchar(48) NOT NULL DEFAULT 'new',
  `meeting_at` datetime(3) DEFAULT NULL,
  `meeting_mode` varchar(48) DEFAULT NULL,
  `meeting_link` longtext,
  `meeting_notes` longtext,
  `assigned_to` char(36) DEFAULT NULL,
  `assigned_name` varchar(255) DEFAULT NULL,
  `quotation_number` varchar(64) DEFAULT NULL,
  `quotation_items` json DEFAULT NULL,
  `quotation_subtotal` decimal(20,6) NOT NULL DEFAULT 0,
  `quotation_tax` decimal(20,6) NOT NULL DEFAULT 0,
  `quotation_total` decimal(20,6) NOT NULL DEFAULT 0,
  `quotation_currency` varchar(16) NOT NULL DEFAULT 'INR',
  `quotation_valid_until` datetime(3) DEFAULT NULL,
  `quotation_notes` longtext,
  `quotation_sent_at` datetime(3) DEFAULT NULL,
  `partnership_started_at` datetime(3) DEFAULT NULL,
  `onboarding_completed_at` datetime(3) DEFAULT NULL,
  `source` varchar(64) NOT NULL DEFAULT 'consultancy_landing',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `consultancy_cases_reference_uidx` (`reference_code`),
  KEY `consultancy_cases_email_idx` (`contact_email`,`created_at`),
  KEY `consultancy_cases_company_user_idx` (`company_user_id`,`updated_at`),
  KEY `consultancy_cases_status_idx` (`status`,`updated_at`),
  KEY `consultancy_cases_assignee_idx` (`assigned_to`,`status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `consultancy_requirements` (
  `id` char(36) NOT NULL,
  `case_id` char(36) NOT NULL,
  `company_user_id` char(36) DEFAULT NULL,
  `created_by` char(36) DEFAULT NULL,
  `assigned_to` char(36) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `department` varchar(191) DEFAULT NULL,
  `openings` int NOT NULL DEFAULT 1,
  `location` longtext,
  `employment_type` varchar(64) DEFAULT NULL,
  `experience_min` decimal(8,2) NOT NULL DEFAULT 0,
  `experience_max` decimal(8,2) NOT NULL DEFAULT 0,
  `skills` json DEFAULT NULL,
  `budget_amount` decimal(20,6) NOT NULL DEFAULT 0,
  `target_date` datetime(3) DEFAULT NULL,
  `description` longtext,
  `status` varchar(48) NOT NULL DEFAULT 'submitted',
  `candidates_submitted` int NOT NULL DEFAULT 0,
  `candidates_shortlisted` int NOT NULL DEFAULT 0,
  `candidates_interviewed` int NOT NULL DEFAULT 0,
  `candidates_hired` int NOT NULL DEFAULT 0,
  `progress_notes` longtext,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `consultancy_requirements_case_idx` (`case_id`,`created_at`),
  KEY `consultancy_requirements_company_idx` (`company_user_id`,`status`,`updated_at`),
  KEY `consultancy_requirements_assignee_idx` (`assigned_to`,`status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `consultancy_activities` (
  `id` char(36) NOT NULL,
  `case_id` char(36) NOT NULL,
  `requirement_id` char(36) DEFAULT NULL,
  `activity_type` varchar(64) NOT NULL,
  `title` varchar(255) NOT NULL,
  `notes` longtext,
  `actor_id` char(36) DEFAULT NULL,
  `actor_name` varchar(255) DEFAULT NULL,
  `actor_role` varchar(64) DEFAULT NULL,
  `visibility` varchar(16) NOT NULL DEFAULT 'internal',
  `metadata` json DEFAULT NULL,
  `occurred_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `consultancy_activities_case_idx` (`case_id`,`occurred_at`),
  KEY `consultancy_activities_requirement_idx` (`requirement_id`,`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `accounts_invoices`
  ADD COLUMN IF NOT EXISTS `consultancy_case_id` char(36) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `consultancy_requirement_id` char(36) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `currency` varchar(16) NOT NULL DEFAULT 'INR',
  ADD COLUMN IF NOT EXISTS `sent_at` datetime(3) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` char(36) DEFAULT NULL;
