-- Business-plan upgrade:
-- - Free trials start only after Razorpay auto-pay authorisation.
-- - Keep role-plan catalog aligned across public pricing and dashboards.

alter table public.role_plan_subscriptions
  drop constraint if exists role_plan_subscriptions_status_chk;

alter table public.role_plan_subscriptions
  add constraint role_plan_subscriptions_status_chk
  check (status in ('pending', 'trialing', 'active', 'expired', 'paused', 'cancelled'));

insert into public.role_plans (
  slug,
  audience_role,
  name,
  description,
  price,
  currency,
  gst_rate,
  billing_cycle,
  duration_days,
  included_job_credits,
  included_job_plan_slug,
  trial_days,
  is_active,
  is_featured,
  sort_order,
  features,
  meta
)
values
  (
    'hr_starter',
    'hr',
    'Starter',
    'Recruiter starter plan with candidate database access, messaging, and interview scheduling.',
    999,
    'INR',
    18,
    'monthly',
    30,
    3,
    'standard',
    60,
    true,
    false,
    10,
    '["Post up to 3 jobs","Candidate search & filters","Send interest to candidates","Resume viewing","Classified job posting","Message templates","Interview scheduling"]'::jsonb,
    '{"category":"hr","selfCheckout":true,"defaultTrial":true,"trialEligible":true,"trialLabel":"2 month free recruiter starter trial","renewalPlanSlug":"hr_starter","listPrice":999,"trialRenewalPrice":999,"studentDbViewLimit":25,"businessFlow":"hr_recruiter_subscription","featureKeys":["candidate_search","candidate_interest","candidate_resume_view","message_templates","interview_scheduling"]}'::jsonb
  ),
  (
    'hr_growth',
    'hr',
    'Growth',
    'Active hiring plan with bulk outreach, campus drives, ATS workflow, and analytics.',
    2499,
    'INR',
    18,
    'monthly',
    30,
    15,
    'classified',
    60,
    true,
    true,
    20,
    '["Everything in Starter","Post up to 15 jobs","Bulk interest messaging","Campus drive access","Full ATS pipeline","Advanced analytics","Hot vacancy posting","Unlimited shortlisting"]'::jsonb,
    '{"category":"hr","selfCheckout":true,"trialEligible":true,"trialLabel":"2 month free recruiter growth trial","renewalPlanSlug":"hr_growth","listPrice":2499,"trialRenewalPrice":2499,"businessFlow":"hr_recruiter_subscription","featureKeys":["candidate_search","candidate_interest","candidate_bulk_interest","candidate_resume_view","campus_drives","ats_full","analytics_advanced","job_post_hot_vacancy","shortlist_unlimited","message_templates","interview_scheduling"]}'::jsonb
  ),
  (
    'hr_enterprise',
    'hr',
    'Enterprise',
    'Large-scale hiring plan with priority listing, dedicated account support, and API access.',
    7999,
    'INR',
    18,
    'monthly',
    30,
    50,
    'hot_vacancy',
    60,
    true,
    false,
    30,
    '["Everything in Growth","Unlimited job postings","Priority listing in search","Dedicated account manager","API access for integration","Custom branding","Bulk campus drives"]'::jsonb,
    '{"category":"hr","selfCheckout":true,"trialEligible":true,"trialLabel":"2 month free recruiter enterprise trial","renewalPlanSlug":"hr_enterprise","listPrice":7999,"trialRenewalPrice":7999,"businessFlow":"hr_recruiter_subscription","featureKeys":["all_features"]}'::jsonb
  ),
  (
    'student_basic',
    'student',
    'Basic',
    'Student starter plan for auto-apply, resume support, mock interviews, and job suggestions.',
    199,
    'INR',
    18,
    'monthly',
    30,
    0,
    null,
    20,
    true,
    false,
    40,
    '["Auto-apply to matched jobs","AI resume builder","Mock interview practice","Skill assessments","AI job suggestions","External job board access"]'::jsonb,
    '{"category":"student","selfCheckout":true,"defaultTrial":true,"trialEligible":true,"trialLabel":"20 day free student basic trial","renewalPlanSlug":"student_basic","listPrice":199,"trialRenewalPrice":199,"businessFlow":"student_subscription","featureKeys":["auto_apply","resume_builder","mock_interview","skill_assessments","ai_suggestions","external_jobs"]}'::jsonb
  ),
  (
    'student_plus',
    'student',
    'Plus',
    'Student growth plan with video resume, priority application, counseling, and company insights.',
    499,
    'INR',
    18,
    'monthly',
    30,
    0,
    null,
    20,
    true,
    true,
    50,
    '["Everything in Basic","Video resume creation","Priority application badge","Career counseling sessions","Company insider insights","Advanced ATS score checker"]'::jsonb,
    '{"category":"student","selfCheckout":true,"trialEligible":true,"trialLabel":"20 day free student plus trial","renewalPlanSlug":"student_plus","listPrice":499,"trialRenewalPrice":499,"businessFlow":"student_subscription","featureKeys":["auto_apply","resume_builder","mock_interview","skill_assessments","ai_suggestions","external_jobs","video_resume","priority_application","career_counseling","company_insights"]}'::jsonb
  ),
  (
    'student_pro',
    'student',
    'Pro',
    'Maximum student plan with unlimited ATS checks and dedicated career support.',
    999,
    'INR',
    18,
    'monthly',
    30,
    0,
    null,
    20,
    true,
    false,
    60,
    '["Everything in Plus","Unlimited ATS checks","Priority placement support","Dedicated career advisor","Exclusive hiring events access","Premium profile badge"]'::jsonb,
    '{"category":"student","selfCheckout":true,"trialEligible":true,"trialLabel":"20 day free student pro trial","renewalPlanSlug":"student_pro","listPrice":999,"trialRenewalPrice":999,"businessFlow":"student_subscription","featureKeys":["all_features"]}'::jsonb
  ),
  (
    'campus_basic',
    'campus_connect',
    'Basic',
    'Campus starter plan for drives, company requests, student management, and placement stats.',
    1499,
    'INR',
    18,
    'monthly',
    30,
    0,
    null,
    30,
    true,
    false,
    70,
    '["Create campus drives","Company connection requests","Student management","Basic placement stats","Drive application tracking"]'::jsonb,
    '{"category":"campus_connect","selfCheckout":true,"defaultTrial":true,"trialEligible":true,"trialLabel":"1 month free campus basic trial","renewalPlanSlug":"campus_basic","listPrice":1499,"trialRenewalPrice":1499,"businessFlow":"campus_connect_subscription","featureKeys":["student_import","campus_drives","company_connections","drive_creation"]}'::jsonb
  ),
  (
    'campus_growth',
    'campus_connect',
    'Growth',
    'Campus growth plan for bulk imports, analytics, report exports, and company directory access.',
    3999,
    'INR',
    18,
    'monthly',
    30,
    0,
    null,
    30,
    true,
    true,
    80,
    '["Everything in Basic","Bulk student CSV upload","Advanced analytics dashboard","Placement report export","Multiple drive management","Company directory access"]'::jsonb,
    '{"category":"campus_connect","selfCheckout":true,"trialEligible":true,"trialLabel":"1 month free campus growth trial","renewalPlanSlug":"campus_growth","listPrice":3999,"trialRenewalPrice":3999,"businessFlow":"campus_connect_subscription","featureKeys":["student_import","campus_drives","company_connections","drive_creation","bulk_student_upload","analytics_advanced","placement_reports","reports_export"]}'::jsonb
  ),
  (
    'campus_enterprise',
    'campus_connect',
    'Enterprise',
    'Institutional campus plan with unlimited drives, priority pipeline, dedicated support, and ERP integration.',
    9999,
    'INR',
    18,
    'monthly',
    30,
    0,
    null,
    30,
    true,
    false,
    90,
    '["Everything in Growth","Unlimited campus drives","Priority placement pipeline","Dedicated support manager","Custom branding & reports","API integration for ERP"]'::jsonb,
    '{"category":"campus_connect","selfCheckout":true,"trialEligible":true,"trialLabel":"1 month free campus enterprise trial","renewalPlanSlug":"campus_enterprise","listPrice":9999,"trialRenewalPrice":9999,"businessFlow":"campus_connect_subscription","featureKeys":["all_features"]}'::jsonb
  )
on conflict (slug) do update
set
  audience_role = excluded.audience_role,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  currency = excluded.currency,
  gst_rate = excluded.gst_rate,
  billing_cycle = excluded.billing_cycle,
  duration_days = excluded.duration_days,
  included_job_credits = excluded.included_job_credits,
  included_job_plan_slug = excluded.included_job_plan_slug,
  trial_days = excluded.trial_days,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order,
  features = excluded.features,
  meta = coalesce(role_plans.meta, '{}'::jsonb) || excluded.meta,
  updated_at = now();
